In [7]:
import pandas as pd
import sqlalchemy
import psycopg2

In [8]:
db_config = {
    'user': 'postgres',
    'password': '12345678',
    'host': 'localhost',
    'port': '5432',
    'database': 'postgres'
}

In [9]:
conn = psycopg2.connect(**db_config)
cursor = conn.cursor()

In [10]:
df = pd.read_csv("items.csv")

the error for below cell is due to trying to insert items data again with same indices. 
the error will not showup if you are adding the data for the first time.

In [11]:

timestamp_columns = ['createdDate', 'dateScanned','finishedDate','modifyDate','pointsAwardedDate','purchaseDate'] 
for col in timestamp_columns:
    if col in df.columns:
        df[col] = df[col].where(pd.notnull(df[col]), None)

df['competitiveProduct'] = df['competitiveProduct'].apply(lambda x: None if pd.isna(x) else x)
df['deleted'] = df['deleted'].apply(lambda x: None if pd.isna(x) else x)
df['needsFetchReview'] = df['needsFetchReview'].apply(lambda x: None if pd.isna(x) else x)
df['preventTargetGapPoints'] = df['preventTargetGapPoints'].where(pd.notnull(df['preventTargetGapPoints']), None)
df['userFlaggedNewItem'] = df['userFlaggedNewItem'].where(pd.notnull(df['userFlaggedNewItem']), None)

table_name = 'items'
for index, row in df.iterrows():
    cursor.execute(
        f"INSERT INTO Fetchrewards.{table_name} (barcode, description, finalPrice, itemPrice, needsFetchReview, partnerItemId, preventTargetGapPoints, quantityPurchased, userFlaggedBarcode, userFlaggedNewItem, userFlaggedPrice, userFlaggedQuantity, receiptId, needsFetchReviewReason, pointsNotAwardedReason, pointsPayerId, rewardsGroup, rewardsProductPartnerId, userFlaggedDescription, originalMetaBriteBarcode, originalMetaBriteDescription, brandCode, competitorRewardsGroup, discountedItemPrice, originalReceiptItemText, itemNumber, originalMetaBriteQuantityPurchased, pointsEarned, targetPrice, competitiveProduct, originalFinalPrice, originalMetaBriteItemPrice, deleted, priceAfterCoupon, metabriteCampaignId) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
        (row['barcode'], row['description'], row['finalPrice'], row['itemPrice'], row['needsFetchReview'], row['partnerItemId'], row['preventTargetGapPoints'], row['quantityPurchased'], row['userFlaggedBarcode'], row['userFlaggedNewItem'], row['userFlaggedPrice'], row['userFlaggedQuantity'], row['receiptId'], row['needsFetchReviewReason'], row['pointsNotAwardedReason'], row['pointsPayerId'], row['rewardsGroup'], row['rewardsProductPartnerId'], row['userFlaggedDescription'], row['originalMetaBriteBarcode'], row['originalMetaBriteDescription'], row['brandCode'], row['competitorRewardsGroup'], row['discountedItemPrice'], row['originalReceiptItemText'], row['itemNumber'], row['originalMetaBriteQuantityPurchased'], row['pointsEarned'], row['targetPrice'], row['competitiveProduct'], row['originalFinalPrice'], row['originalMetaBriteItemPrice'], row['deleted'], row['priceAfterCoupon'], row['metabriteCampaignId'])
    )

conn.commit()

UniqueViolation: duplicate key value violates unique constraint "items_pkey"
DETAIL:  Key (receiptid, partneritemid)=(5ff1e1eb0a720f0523000575, 1) already exists.

In [12]:
df

,barcode,description,finalPrice,itemPrice,needsFetchReview,partnerItemId,preventTargetGapPoints,quantityPurchased,userFlaggedBarcode,userFlaggedNewItem,...,itemNumber,originalMetaBriteQuantityPurchased,pointsEarned,targetPrice,competitiveProduct,originalFinalPrice,originalMetaBriteItemPrice,deleted,priceAfterCoupon,metabriteCampaignId
0,4011,ITEM NOT FOUND,26.00,26.00,False,1,True,5.0,4.011000e+03,True,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN
1,4011,ITEM NOT FOUND,1.00,1.00,None,1,None,1.0,NaN,None,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN
2,-2147483648,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,10.00,10.00,True,2,True,1.0,2.840064e+10,True,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN
3,0,NaN,NaN,NaN,False,1,True,NaN,4.011000e+03,True,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN
4,4011,ITEM NOT FOUND,28.00,28.00,False,1,True,4.0,4.011000e+03,True,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4332,0,thindust summer face mask - sun protection nec...,11.99,11.99,None,1,None,1.0,NaN,None,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,11.99,NaN
4333,0,mueller austria hypergrind precision electric ...,22.97,22.97,None,0,None,1.0,NaN,None,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,22.97,NaN
4334,0,thindust summer face mask - sun protection nec...,11.99,11.99,None,1,None,1.0,NaN,None,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,11.99,NaN
4335,0,mueller austria hypergrind precision electric ...,22.97,22.97,None,0,None,1.0,NaN,None,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,22.97,NaN
4336,0,thindust summer face mask - sun protection nec...,11.99,11.99,None,1,None,1.0,NaN,None,...,NaN,NaN,NaN,NaN,None,NaN,NaN,None,11.99,NaN